import type { PlaylistSummary, CuratedPlaylistSource } from "../../api/client";
import { hasCleanupIssues, type PlaylistScanSummary } from "./cleanupInsights";

export const PlaylistSortKey = {
  LibraryOrder: "library-order",
  NameAsc: "name-asc",
  NameDesc: "name-desc",
  TracksDesc: "tracks-desc",
  TracksAsc: "tracks-asc",
  OwnerAsc: "owner-asc",
  AccessViewOnlyFirst: "access-viewonly",
  IssuesDesc: "issues-desc",
} as const;

export type PlaylistSortKey = (typeof PlaylistSortKey)[keyof typeof PlaylistSortKey];

const SORT_STORAGE_KEY = "spotify-curator-playlist-sort";
const LEGACY_ACCESS_EDITABLE_SORT = "access-editable";

export const playlistSortOptions: { value: PlaylistSortKey; label: string }[] = [
  { value: PlaylistSortKey.LibraryOrder, label: "Spotify library order" },
  { value: PlaylistSortKey.NameAsc, label: "Name (A–Z)" },
  { value: PlaylistSortKey.NameDesc, label: "Name (Z–A)" },
  { value: PlaylistSortKey.TracksDesc, label: "Most tracks" },
  { value: PlaylistSortKey.TracksAsc, label: "Fewest tracks" },
  { value: PlaylistSortKey.OwnerAsc, label: "Owner (A–Z)" },
  { value: PlaylistSortKey.AccessViewOnlyFirst, label: "View only section first" },
  { value: PlaylistSortKey.IssuesDesc, label: "Most issues" },
];

function compareText(left: string, right: string): number {
  return left.localeCompare(right, undefined, { sensitivity: "base" });
}

function issueScore(
  playlist: PlaylistSummary,
  summaries: Record<string, PlaylistScanSummary>,
): number {
  const summary = summaries[playlist.id];
  if (!summary || !hasCleanupIssues(summary)) {
    return 0;
  }
  return summary.duplicate_tracks + summary.unavailable_tracks;
}

/** Whether playlists are split into editable / view-only sections. */
export function usesAccessGrouping(sortKey: PlaylistSortKey): boolean {
  return sortKey !== PlaylistSortKey.OwnerAsc;
}

/** Sort key applied inside each access group (section order sorts use library order within groups). */
export function withinGroupSortKey(sortKey: PlaylistSortKey): PlaylistSortKey {
  if (sortKey === PlaylistSortKey.AccessViewOnlyFirst) {
    return PlaylistSortKey.LibraryOrder;
  }
  return sortKey;
}

export function sortPlaylists(
  playlists: PlaylistSummary[],
  sortKey: PlaylistSortKey,
  summaries: Record<string, PlaylistScanSummary>,
): PlaylistSummary[] {
  const sorted = [...playlists];
  sorted.sort((left, right) => {
    switch (sortKey) {
      case PlaylistSortKey.NameAsc:
        return compareText(left.name, right.name);
      case PlaylistSortKey.NameDesc:
        return compareText(right.name, left.name);
      case PlaylistSortKey.TracksDesc:
        return right.track_count - left.track_count || compareText(left.name, right.name);
      case PlaylistSortKey.TracksAsc:
        return left.track_count - right.track_count || compareText(left.name, right.name);
      case PlaylistSortKey.OwnerAsc:
        return compareText(left.owner, right.owner) || compareText(left.name, right.name);
      case PlaylistSortKey.AccessViewOnlyFirst:
        return (
          Number(left.can_edit) - Number(right.can_edit) ||
          compareText(left.owner, right.owner) ||
          compareText(left.name, right.name)
        );
      case PlaylistSortKey.IssuesDesc:
        return (
          issueScore(right, summaries) - issueScore(left, summaries) ||
          compareText(left.name, right.name)
        );
      case PlaylistSortKey.LibraryOrder:
      default:
        return (
          (left.library_order ?? Number.MAX_SAFE_INTEGER) -
            (right.library_order ?? Number.MAX_SAFE_INTEGER) || compareText(left.name, right.name)
        );
    }
  });
  return sorted;
}

export interface PlaylistAccessGroup {
  id: "curated" | "editable" | "view-only";
  label: string;
  description: string;
  playlists: PlaylistSummary[];
}

function isCuratedPlaylist(
  playlist: PlaylistSummary,
  curatedSources: Record<string, CuratedPlaylistSource>,
): boolean {
  return Boolean(curatedSources[playlist.id]);
}

export function groupPlaylistsByAccess(
  playlists: PlaylistSummary[],
  options: {
    viewOnlyFirst?: boolean;
    curatedSources?: Record<string, CuratedPlaylistSource>;
  } = {},
): PlaylistAccessGroup[] {
  const viewOnlyFirst = options.viewOnlyFirst ?? false;
  const curatedSources = options.curatedSources ?? {};
  const curated = playlists.filter(
    (playlist) => playlist.can_edit && isCuratedPlaylist(playlist, curatedSources),
  );
  const editable = playlists.filter(
    (playlist) => playlist.can_edit && !isCuratedPlaylist(playlist, curatedSources),
  );
  const viewOnly = playlists.filter((playlist) => !playlist.can_edit);

  const curatedGroup: PlaylistAccessGroup = {
    id: "curated",
    label: "Curated",
    description: "Playlists generated by Discover or Mood Concierge — not hand-built.",
    playlists: curated,
  };
  const editableGroup: PlaylistAccessGroup = {
    id: "editable",
    label: "Your playlists",
    description: "Hand-built playlists you can edit and scan for cleanup issues.",
    playlists: editable,
  };
  const viewOnlyGroup: PlaylistAccessGroup = {
    id: "view-only",
    label: "View only",
    description: "Followed or shared playlists owned by someone else.",
    playlists: viewOnly,
  };

  const groups: PlaylistAccessGroup[] = [];
  if (viewOnlyFirst) {
    if (viewOnly.length > 0) {
      groups.push(viewOnlyGroup);
    }
    if (curated.length > 0) {
      groups.push(curatedGroup);
    }
    if (editable.length > 0) {
      groups.push(editableGroup);
    }
  } else {
    if (curated.length > 0) {
      groups.push(curatedGroup);
    }
    if (editable.length > 0) {
      groups.push(editableGroup);
    }
    if (viewOnly.length > 0) {
      groups.push(viewOnlyGroup);
    }
  }
  return groups;
}

export function organizePlaylists(
  playlists: PlaylistSummary[],
  sortKey: PlaylistSortKey,
  summaries: Record<string, PlaylistScanSummary>,
  curatedSources: Record<string, CuratedPlaylistSource> = {},
): PlaylistAccessGroup[] {
  if (!usesAccessGrouping(sortKey)) {
    const curated = playlists.filter(
      (playlist) => playlist.can_edit && isCuratedPlaylist(playlist, curatedSources),
    );
    const rest = playlists.filter(
      (playlist) => !playlist.can_edit || !isCuratedPlaylist(playlist, curatedSources),
    );
    const groups: PlaylistAccessGroup[] = [];
    if (curated.length > 0) {
      groups.push({
        id: "curated",
        label: "Curated",
        description: "",
        playlists: sortPlaylists(curated, sortKey, summaries),
      });
    }
    groups.push({
      id: "editable",
      label: "",
      description: "",
      playlists: sortPlaylists(rest, sortKey, summaries),
    });
    return groups;
  }

  const curated = playlists.filter(
    (playlist) => playlist.can_edit && isCuratedPlaylist(playlist, curatedSources),
  );
  const editable = playlists.filter(
    (playlist) => playlist.can_edit && !isCuratedPlaylist(playlist, curatedSources),
  );
  const viewOnly = playlists.filter((playlist) => !playlist.can_edit);
  const withinSort = withinGroupSortKey(sortKey);

  const sortedCurated = sortPlaylists(curated, withinSort, summaries);
  const sortedEditable = sortPlaylists(editable, withinSort, summaries);
  const sortedViewOnly = sortPlaylists(viewOnly, withinSort, summaries);
  const viewOnlyFirst = sortKey === PlaylistSortKey.AccessViewOnlyFirst;

  return groupPlaylistsByAccess([...sortedCurated, ...sortedEditable, ...sortedViewOnly], {
    viewOnlyFirst,
    curatedSources,
  }).map((group) => ({
    ...group,
    playlists:
      group.id === "curated"
        ? sortedCurated
        : group.id === "editable"
          ? sortedEditable
          : sortedViewOnly,
  }));
}

export function loadPlaylistSortKey(): PlaylistSortKey {
  const stored = localStorage.getItem(SORT_STORAGE_KEY);
  if (stored === LEGACY_ACCESS_EDITABLE_SORT) {
    return PlaylistSortKey.LibraryOrder;
  }
  if (stored && playlistSortOptions.some((option) => option.value === stored)) {
    return stored as PlaylistSortKey;
  }
  return PlaylistSortKey.LibraryOrder;
}

export function savePlaylistSortKey(sortKey: PlaylistSortKey): void {
  localStorage.setItem(SORT_STORAGE_KEY, sortKey);
}

export const defaultPlaylistSortKey = PlaylistSortKey.LibraryOrder;

export function usePlaylistOrganizeDefaults() {
  return {
    sortKey: loadPlaylistSortKey(),
  };
}
